"""
Incident Report Agent
=====================
Responsibilities:
- Generate structured RCA incident report
- For real repos: commit fix files to a new branch, then create PR
- For demo mode: simulate PR URL
- Post explanatory comment on the failed run
"""

import logging
from datetime import datetime

from agents.state import WorkflowState, IncidentReport
from tools.github_tool import GitHubTool
from config import settings

logger = logging.getLogger(__name__)


def _generate_incident_report(state: WorkflowState) -> IncidentReport:
    """Generate a structured incident report from workflow state."""
    classification = state.get("parsed_failure") or {}
    fix = state.get("proposed_fix") or {}
    validation = state.get("validation_result") or {}
    messages = state.get("agent_messages") or []
    retry_count = state.get("retry_count", 0)

    timeline = [
        {
            "timestamp": msg.get("timestamp", ""),
            "event": f"[{msg.get('agent', '')}] {msg.get('message', '')[:200]}",
        }
        for msg in messages
    ]

    failure_type = classification.get("failure_type", "unknown")
    severity_map = {
        "docker_build_failure": "high",
        "dep_conflict": "high",
        "missing_env_var": "medium",
        "import_error": "medium",
        "test_failure": "medium",
        "ts_build_error": "low",
        "npm_dep_conflict": "low",
        "syntax_error": "high",
    }
    severity = severity_map.get(failure_type, "medium")
    confidence = classification.get("confidence", 0.5)
    evidence = (classification.get("error_messages") or [])[:5]

    remediation_steps = []
    if fix:
        remediation_steps.append(fix.get("strategy", "Review logs manually"))
        for patch in (fix.get("patches") or [])[:5]:
            remediation_steps.append(
                f"File `{patch.get('file', 'unknown')}`: {patch.get('explanation', '')}"
            )
        for cmd in (fix.get("commands_to_run") or [])[:3]:
            remediation_steps.append(f"Run: `{cmd}`")

    validation_status = "✅ Validated" if validation.get("passed") else "⚠️ Partial fix"
    patches = fix.get("patches") or []

    pr_description = f"""## 🤖 Autonomous CI/CD Fix

**Generated by:** Autonomous CI/CD Failure Fixer  
**Failure Type:** `{failure_type}`  
**Confidence:** {confidence * 100:.0f}%  
**Severity:** {severity.upper()}  
**Validation:** {validation_status}  
**Retries:** {retry_count}

### Root Cause
{classification.get('reasoning', 'See logs')}

### Fix Applied
{fix.get('explanation', fix.get('strategy', 'No fix details available'))}

### Files Changed
{chr(10).join([f"- `{p.get('file', '?')}`: {p.get('explanation', '')}" for p in patches[:5]]) or "- No file changes (advisory fix)"}

### Validation
{validation.get('summary', 'Not validated')}

### Evidence
{chr(10).join([f"- `{e}`" for e in evidence[:3]]) or "- See workflow logs"}

---
*This PR was automatically generated. Please review all changes before merging.*
"""

    return IncidentReport(
        title=f"[Auto-Fix] {failure_type.replace('_', ' ').title()} in {state.get('repo_name', 'unknown')}",
        severity=severity,
        timeline=timeline,
        root_cause_summary=classification.get("reasoning", "Unknown root cause"),
        evidence=evidence,
        fix_applied=fix.get("strategy", "No fix applied"),
        confidence=confidence,
        remediation_steps=remediation_steps,
        pr_description=pr_description,
    )


def _try_create_real_pr(state: WorkflowState, report: IncidentReport) -> tuple:
    """
    Full real PR flow:
    1. Create a fix branch
    2. Commit all patched files to it
    3. Open a PR
    4. Post a comment on the failed run

    Returns (pr_url, comment_url). Either may be None on failure.
    """
    github = GitHubTool()
    owner = state.get("repo_owner", "")
    # Guard against repo_name being "owner/repo" vs just "repo"
    repo = state.get("repo_name", "").split("/")[-1]
    base_branch = state.get("repo_branch", "main")
    fix = state.get("proposed_fix") or {}
    patches = fix.get("patches") or []

    failure_type = (state.get("parsed_failure") or {}).get("failure_type", "unknown")
    short_id = state["workflow_id"][:8]
    fix_branch = f"autofix/{short_id}-{failure_type}"

    # ── Diagnostics ────────────────────────────────────────────────────────────
    logger.info(
        f"[IncidentAgent] _try_create_real_pr: "
        f"owner={owner!r} repo={repo!r} base={base_branch!r} "
        f"fix_branch={fix_branch!r} patches={len(patches)}"
    )
    logger.info(f"[IncidentAgent] github_token set: {bool(settings.github_token)}")

    for i, p in enumerate(patches):
        repl_len = len(p.get("replacement") or p.get("content") or "")
        logger.info(
            f"[IncidentAgent] Patch[{i}]: file={p.get('file')!r} "
            f"replacement_chars={repl_len}"
        )
        if repl_len == 0:
            logger.warning(
                f"[IncidentAgent] Patch[{i}] has no content — will be skipped by commit_patches. "
                "fix_agent must populate the 'replacement' field."
            )

    # ── Step 1+2: commit patches to fix branch ─────────────────────────────────
    pr_url = ""
    comment_url = ""

    if not patches:
        logger.warning(
            "[IncidentAgent] proposed_fix.patches is empty — "
            "nothing to commit, skipping PR creation. "
            "Check that fix_agent generated at least one patch with a non-empty 'replacement'."
        )
        return None, None

    committed = github.commit_patches(
        owner=owner,
        repo=repo,
        branch=fix_branch,
        patches=patches,
        base_branch=base_branch,
    )

    if not committed:
        logger.warning(
            "[IncidentAgent] commit_patches returned False — "
            "no files were written to the fix branch. "
            "Check GitHubTool logs above for the exact reason. "
            "PR will be skipped."
        )
        return None, None

    # ── Step 3: create PR ──────────────────────────────────────────────────────
    logger.info(f"[IncidentAgent] Patches committed — creating PR '{fix_branch}' → '{base_branch}'")
    pr_url = github.create_pull_request(
        owner=owner,
        repo=repo,
        title=report["title"],
        body=report["pr_description"],
        branch=fix_branch,
        base_branch=base_branch,
    )

    if pr_url:
        logger.info(f"[IncidentAgent] ✅ PR created: {pr_url}")
    else:
        logger.error(
            "[IncidentAgent] ❌ create_pull_request returned empty string. "
            "Check GitHubTool logs for the HTTP status and GitHub error message. "
            "Common causes: (1) token lacks 'repo' scope, "
            "(2) branch has no commits ahead of base, "
            "(3) a PR for this branch already exists."
        )

    # ── Step 4: comment on the failed run ──────────────────────────────────────
    run_id = state.get("workflow_run_id", "")
    if run_id:
        pr_ref = f"\n\nFix PR: {pr_url}" if pr_url else ""
        comment_url = github.post_workflow_comment(
            owner=owner,
            repo=repo,
            run_id=run_id,
            comment=(
                f"🤖 **Autonomous CI/CD Fixer** analyzed this failure.\n\n"
                f"Root cause: `{failure_type}`\n"
                f"Confidence: {int((state.get('parsed_failure') or {}).get('confidence', 0) * 100)}%"
                f"{pr_ref}"
            ),
        )

    return pr_url or None, comment_url or None


def incident_agent(state: WorkflowState) -> WorkflowState:
    """Incident report agent node for LangGraph."""
    logger.info(f"[IncidentAgent] Starting for workflow {state['workflow_id']}")
    new_state = {**state, "current_agent": "incident_report"}

    try:
        report = _generate_incident_report(state)

        # Choose PR strategy based on mode
        is_demo = state.get("trigger_event") in ("demo",) or not settings.github_token

        if is_demo:
            repo_name = state.get("repo_name", "demo-repo")
            pr_url = f"https://github.com/{repo_name}/pull/42"
            comment_url = f"https://github.com/{repo_name}/actions/runs/999"
            logger.info(
                f"[IncidentAgent] DEMO MODE active (trigger_event={state.get('trigger_event')!r}, "
                f"token_set={bool(settings.github_token)}) — simulated PR at {pr_url}"
            )
        else:
            pr_url, comment_url = _try_create_real_pr(state, report)
            logger.info(f"[IncidentAgent] Real PR result: {pr_url!r}")

        new_state["incident_report"] = dict(report) if hasattr(report, "__dict__") else report
        new_state["pull_request_url"] = pr_url
        new_state["github_comment_url"] = comment_url

        validation = state.get("validation_result") or {}
        if validation.get("passed"):
            final_status = "success"
        elif state.get("retry_count", 0) >= settings.max_retries:
            final_status = "partial"
        else:
            final_status = "success"

        new_state["final_status"] = final_status
        new_state["agent_messages"] = (state.get("agent_messages") or []) + [{
            "agent": "incident_report",
            "timestamp": datetime.utcnow().isoformat(),
            "event": "completed",
            "message": f"Report generated. PR: {pr_url or 'N/A'}. Status: {final_status}",
            "data": {"pr_url": pr_url, "final_status": final_status},
        }]

        logger.info(f"[IncidentAgent] Done. status={final_status} pr={pr_url!r}")
        return new_state

    except Exception as e:
        logger.error(f"[IncidentAgent] Failed: {e}", exc_info=True)
        new_state["final_status"] = "failed"
        new_state["error"] = str(e)
        new_state["agent_messages"] = (state.get("agent_messages") or []) + [{
            "agent": "incident_report",
            "timestamp": datetime.utcnow().isoformat(),
            "event": "failed",
            "message": str(e),
        }]
        return new_state