"""
Incident Report Agent
=====================
Responsibilities:
- Generate structured RCA incident report
- Create GitHub pull request with fix
- Post explanatory comment on failed GitHub Actions run
- Summarize the full workflow timeline

This is the terminal agent — all outputs are created here.
"""

import json
import logging
from datetime import datetime
from agents.state import WorkflowState, IncidentReport
from tools.github_tool import GitHubTool
from config import settings

logger = logging.getLogger(__name__)


def _generate_incident_report(state: WorkflowState) -> IncidentReport:
    """Generate a structured incident report from workflow state."""
    classification = state.get("parsed_failure", {})
    fix = state.get("proposed_fix", {})
    validation = state.get("validation_result", {})
    messages = state.get("agent_messages", [])
    retry_count = state.get("retry_count", 0)

    # Build timeline from agent messages
    timeline = []
    for msg in messages:
        timeline.append({
            "timestamp": msg.get("timestamp", ""),
            "agent": msg.get("agent", ""),
            "event": msg.get("event", ""),
            "description": msg.get("message", "")[:200],
        })

    # Determine severity
    failure_type = classification.get("failure_type", "unknown")
    severity_map = {
        "docker_build_failure": "high",
        "dep_conflict": "high",
        "missing_env_var": "medium",
        "import_error": "medium",
        "test_failure": "medium",
        "ts_build_error": "low",
        "npm_dep_conflict": "low",
        "syntax_error": "high",
    }
    severity = severity_map.get(failure_type, "medium")

    # Confidence from RCA
    confidence = classification.get("confidence", 0.5)

    # Build evidence list
    evidence = classification.get("error_messages", [])[:5]
    affected_files = classification.get("affected_files", [])

    # Build remediation steps
    remediation_steps = []
    if fix:
        remediation_steps.append(fix.get("strategy", "Review logs manually"))
        for patch in fix.get("patches", [])[:5]:
            remediation_steps.append(
                f"File: {patch.get('file', 'unknown')} — {patch.get('explanation', '')}"
            )
        for cmd in fix.get("commands_to_run", [])[:3]:
            remediation_steps.append(f"Run: `{cmd}`")

    # PR description
    validation_status = "✅ Validated" if validation.get("passed") else "⚠️ Partial fix (validation failed)"
    pr_description = f"""## 🤖 Autonomous CI/CD Fix

**Generated by:** Autonomous CI/CD Failure Fixer
**Failure Type:** `{failure_type}`
**Confidence:** {confidence*100:.0f}%
**Severity:** {severity.upper()}
**Validation:** {validation_status}
**Retries:** {retry_count}

### Root Cause
{classification.get('reasoning', 'See error messages below')}

### Fix Applied
{fix.get('explanation', 'No fix details available')}

### Changes Made
{chr(10).join([f"- `{p.get('file', 'unknown')}`: {p.get('explanation', '')}" for p in fix.get('patches', [])[:5]]) or "- No file changes (advisory fix)"}

### Validation
{validation.get('summary', 'Not validated')}

### Evidence
{chr(10).join([f"- `{e}`" for e in evidence[:3]]) or "- See workflow logs"}

---
*This PR was automatically generated. Please review all changes before merging.*
"""

    report: IncidentReport = {
        "title": f"[Auto-Fix] {failure_type.replace('_', ' ').title()} in {state.get('repo_name', 'unknown')}",
        "severity": severity,
        "timeline": timeline,
        "root_cause_summary": classification.get("reasoning", "Unknown root cause"),
        "evidence": evidence,
        "fix_applied": fix.get("strategy", "No fix applied"),
        "confidence": confidence,
        "remediation_steps": remediation_steps,
        "pr_description": pr_description,
    }

    return report


def _try_create_pr(state: WorkflowState, report: IncidentReport) -> tuple[str | None, str | None]:
    """
    Attempt to create a GitHub PR and comment.
    Returns (pr_url, comment_url) or (None, None) in demo mode.
    """
    if settings.demo_mode or not settings.github_token:
        # Demo mode: return simulated URLs
        repo_name = state.get("repo_name", "demo-repo")
        pr_url = f"https://github.com/{repo_name}/pull/42"
        comment_url = f"https://github.com/{repo_name}/actions/runs/{state.get('workflow_run_id', '999')}"
        logger.info(f"[IncidentAgent] Demo mode: simulated PR at {pr_url}")
        return pr_url, comment_url

    try:
        github = GitHubTool()
        fix = state.get("proposed_fix", {})

        # Create branch name
        branch_name = f"autofix/{state['workflow_id'][:8]}-{state.get('parsed_failure', {}).get('failure_type', 'unknown')}"

        pr_url = github.create_pull_request(
            owner=state["repo_owner"],
            repo=state["repo_name"].split("/")[-1],
            title=report["title"],
            body=report["pr_description"],
            branch=branch_name,
            base_branch=state.get("repo_branch", "main"),
        )

        comment_url = github.post_workflow_comment(
            owner=state["repo_owner"],
            repo=state["repo_name"].split("/")[-1],
            run_id=state.get("workflow_run_id", ""),
            comment=f"🤖 **Autonomous CI/CD Fixer** has analyzed this failure.\n\nRoot cause: `{state.get('parsed_failure', {}).get('failure_type', 'unknown')}`\n\nA fix PR has been created: {pr_url}",
        )

        return pr_url, comment_url

    except Exception as e:
        logger.warning(f"[IncidentAgent] Could not create PR/comment: {e}")
        return None, None


def incident_agent(state: WorkflowState) -> WorkflowState:
    """Incident report agent node for LangGraph."""
    logger.info(f"[IncidentAgent] Starting for workflow {state['workflow_id']}")
    new_state = {**state, "current_agent": "incident_report"}

    try:
        # Generate the report
        report = _generate_incident_report(state)

        # Attempt GitHub PR creation
        pr_url, comment_url = _try_create_pr(state, report)

        new_state["incident_report"] = report
        new_state["pull_request_url"] = pr_url
        new_state["github_comment_url"] = comment_url

        # Determine final status
        validation = state.get("validation_result", {})
        if validation.get("passed"):
            final_status = "success"
        elif state.get("retry_count", 0) >= settings.max_retries:
            final_status = "partial"
        else:
            final_status = "success"

        new_state["final_status"] = final_status

        new_state["agent_messages"] = state.get("agent_messages", []) + [{
            "agent": "incident_report",
            "timestamp": datetime.utcnow().isoformat(),
            "event": "completed",
            "message": f"Incident report generated. PR: {pr_url or 'N/A'}. Status: {final_status}",
            "data": {
                "pr_url": pr_url,
                "comment_url": comment_url,
                "severity": report["severity"],
                "final_status": final_status,
            },
        }]

        logger.info(f"[IncidentAgent] Completed. Status={final_status}, PR={pr_url}")
        return new_state

    except Exception as e:
        logger.error(f"[IncidentAgent] Failed: {e}")
        new_state["final_status"] = "failed"
        new_state["error"] = f"Incident report agent failed: {str(e)}"
        new_state["agent_messages"] = state.get("agent_messages", []) + [{
            "agent": "incident_report",
            "timestamp": datetime.utcnow().isoformat(),
            "event": "failed",
            "message": str(e),
        }]
        return new_state